# Generated by Django 3.0.4 on 2020-03-23 21:36

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path),
        ),
    ]
