# Generated by Django 3.0.4 on 2020-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200323_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True)),
                ('modificado', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('feature', models.CharField(max_length=100)),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Telefone'), ('lni-users', 'Usuarios'), ('lni-layers', 'Design'), ('lni-leaf', 'Folha'), ('lni-rocket', 'Foguete')], max_length=16)),
                ('descricao', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Feature Left',
                'verbose_name_plural': 'Features Left',
            },
        ),
        migrations.CreateModel(
            name='FeatureRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True)),
                ('modificado', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('feature', models.CharField(max_length=100)),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Telefone'), ('lni-users', 'Usuarios'), ('lni-layers', 'Design'), ('lni-leaf', 'Folha'), ('lni-rocket', 'Foguete')], max_length=16)),
                ('descricao', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Feature Right',
                'verbose_name_plural': 'Features Right',
            },
        ),
    ]
